hook.Add("LoadAnimationClasses", "impulseHL2RPAnimClasses", function()
	impulse.Anim.SetModelClass("models/dpfilms/metropolice/hdpolice.mdl", "metrocop")
	impulse.Anim.SetModelClass("models/dpfilms/metropolice/civil_medic.mdl", "metrocop")
	impulse.Anim.SetModelClass("models/dpfilms/metropolice/hl2beta_police.mdl", "metrocop")
	impulse.Anim.SetModelClass("models/dpfilms/metropolice/retrocop.mdl", "metrocop")
	impulse.Anim.SetModelClass("models/dpfilms/metropolice/elite_police.mdl", "metrocop")
	impulse.Anim.SetModelClass("models/dpfilms/metropolice/policetrench.mdl", "metrocop")
	impulse.Anim.SetModelClass("models/dpfilms/metropolice/hl2concept.mdl", "metrocop")
	impulse.Anim.SetModelClass("models/dpfilms/metropolice/blacop.mdl", "metrocop")
	impulse.Anim.SetModelClass("models/vortiblue1.mdl", "vort")
end)
